Add useful components and fix .gitignore
Dualog-students/Diplomatic pull request #2
Opened 2018-06-20 08:41 UTC by IsakSundeSingh

Adds some triggers, converters and behaviors.

2018-06-20 08:47 UTC, fredeil commented on Diplomatic/Utils/Converters/PositiveLength.cs
> +            return (int)value > 0;
Will crash, consider using C# 7.0 pattern matching instead

2018-06-20 08:47 UTC, fredeil commented on Diplomatic/Utils/Converters/RegexMatch.cs
> +            return regex.IsMatch(text);
You should replace this inefficient code with a call to the static [Regex.IsMatch(String, String)](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.ismatch#System_Text_RegularExpressions_Regex_IsMatch_System_String_System_String_) method.

2018-06-20 08:50 UTC, fredeil commented
Should add an .editorconfig to the project too.
https://github.com/Dualog-students/dualog-students.github.io/blob/master/.editorconfig

2018-06-21 06:58 UTC, MaxJohansen commented
I suggest the following additions to the root element of the editorconfig:

```
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

Because trailing whitespace is gross and final newlines are POSIX standard.

2018-06-21 06:59 UTC, MaxJohansen requested changes
I suggest the following additions to the root element of the editorconfig:

```
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

Because trailing whitespace is gross and final newlines are POSIX standard.

2018-06-21 07:36 UTC, vebjornhaugland approved these changes
Looks good

2018-06-21 07:38 UTC, IsakSundeSingh commented
Let's 🚢 🇮🇹

2018-06-21 07:40 UTC, MaxJohansen approved these changes

2018-06-21 07:40 UTC, merged